[package]
name = "complexipy"
version = "0.1.0"
edition = "2021"
authors = ["Robin Quintero <rohaquinlop301@gmail.com>"]
license = "MIT"
description = "Calculate the cognitive complexity of your python files"
readme = "README.md"
homepage = "https://github.com/rohaquinlop/complexipy"
repository = "https://github.com/rohaquinlop/complexipy"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "complexipy"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"
rustpython-parser = "0.3.0"
